### ISSUE TITLE
java.io.FileNotFoundException: cloudmc:cloudlogo.png

### ISSUE THREAD

**Issue by Ry4nnnnn** [cloudclientdev/cloudclient#50]
i started client in intellij idea, but java.io.FileNotFoundException: cloudmc:cloudlogo.png

**Comment by NerdHaxx** [comment]
yeah its a thing with the dev environment it gets auto fixed after u build the jar and use the mod from minecraft launcher

**Comment by Ry4nnnnn** [comment]
and client crashed when i changed the font

**Comment by Ry4nnnnn** [comment]
not only in intellij idea, but also use the mod from minecraft launcher

**Comment by NerdHaxx** [comment]
hmm what os are u using?
it could be caused by ur os (the font crash)
and about the cloudlogo.png check if it is placed in the same path as it is written in code its possible something happend during the setup process and you may have to re-setup the dev workspace

thats all the solutions i can think of right now it should normally just work fine but this is a weird case
