### ISSUE TITLE
Account Manager

### ISSUE THREAD

**Issue by NerdHaxx** [CloudClientDev/cloudclient#9]
an account manager that can also add cracked accounts would be really great for this client. ima be honest the client is really great and clean and i look forward to contributing my own changes to this project (if it doesn't get discontinued after a month of release that is lol i sure hope that this project stays for a long time) :p

**Comment by NotNeliz** [comment]
Yea account manager can be a pretty good idea but that is more a suggestion then an issue.
(You can suggest stuff in the discord server https://dsc.gg/cloudclientmc)
Duplicat already said several times that cracked will never be supported because of mojang's Terms of Service.
But it is a mod so I think it would be possible to add in the mod folder in your cracked Minecraft client.

Hope this helps,
Neliz

**Comment by duplidev** [comment]
This is for reporting bugs and issues, please use the discord server from above to suggest new changes.
